<script type="text/javascript">
    var _dadataSettings = {};
    _dadataSettings['billing'] = {};
    _dadataSettings['shipping'] = {};
    _dadataSettings['customer'] = {};
    _dadataSettings['other'] = {};

    _dadataSettings['token'] = "<?php echo Mage::getStoreConfig('dadata/api_settings/token'); ?>";

    _dadataSettings.billing['address'] = "<?php echo Mage::getStoreConfig('dadata/billing_info_settings/address'); ?>";
    _dadataSettings.billing['city'] = "<?php echo Mage::getStoreConfig('dadata/billing_info_settings/city'); ?>";
    _dadataSettings.billing['first_name'] = "<?php echo Mage::getStoreConfig('dadata/billing_info_settings/first_name'); ?>";
    _dadataSettings.billing['middle_name'] = "<?php echo Mage::getStoreConfig('dadata/billing_info_settings/middle_name'); ?>";
    _dadataSettings.billing['last_name'] = "<?php echo Mage::getStoreConfig('dadata/billing_info_settings/last_name'); ?>";
    _dadataSettings.billing['postal_code'] = "<?php echo Mage::getStoreConfig('dadata/billing_info_settings/postal_code'); ?>";

    _dadataSettings.shipping['address'] = "<?php echo Mage::getStoreConfig('dadata/shipping_info_settings/address'); ?>";
    _dadataSettings.shipping['city'] = "<?php echo Mage::getStoreConfig('dadata/shipping_info_settings/city'); ?>";
    _dadataSettings.shipping['first_name'] = "<?php echo Mage::getStoreConfig('dadata/shipping_info_settings/first_name'); ?>";
    _dadataSettings.shipping['middle_name'] = "<?php echo Mage::getStoreConfig('dadata/shipping_info_settings/middle_name'); ?>";
    _dadataSettings.shipping['last_name'] = "<?php echo Mage::getStoreConfig('dadata/shipping_info_settings/last_name'); ?>";
    _dadataSettings.shipping['postal_code'] = "<?php echo Mage::getStoreConfig('dadata/shipping_info_settings/postal_code'); ?>";

    _dadataSettings.customer['address'] = "<?php echo Mage::getStoreConfig('dadata/customer_info_settings/address'); ?>";
    _dadataSettings.customer['city'] = "<?php echo Mage::getStoreConfig('dadata/customer_info_settings/city'); ?>";
    _dadataSettings.customer['first_name'] = "<?php echo Mage::getStoreConfig('dadata/customer_info_settings/first_name'); ?>";
    _dadataSettings.customer['middle_name'] = "<?php echo Mage::getStoreConfig('dadata/customer_info_settings/middle_name'); ?>";
    _dadataSettings.customer['last_name'] = "<?php echo Mage::getStoreConfig('dadata/customer_info_settings/last_name'); ?>";
    _dadataSettings.customer['postal_code'] = "<?php echo Mage::getStoreConfig('dadata/customer_info_settings/postal_code'); ?>";

    _dadataSettings.other['fullnames'] = "<?php echo Mage::getStoreConfig('dadata/other_settings/fullnames'); ?>";
</script>